header:
  version: 14

distro: poky
build_system: oe
machine: raspberrypi3-64
target: core-image-minimal

repos:
  poky:
    url: "https://git.yoctoproject.org/poky"
    refspec: kirkstone
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-raspberrypi:
    url: https://git.yoctoproject.org/meta-raspberrypi
    refspec: kirkstone
    path: "layers/meta-raspberrypi"

  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded.git"
    refspec: kirkstone
    path: "layers/meta-openembedded"
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-filesystems:

  bitbake:
    url: "https://git.openembedded.org/bitbake"
    refspec: "2.0"
    path: "layers/openembedded-core/bitbake"
    layers:
      .: excluded


local_conf_header:
  custom-local-conf: |
    ACCEPT_FSL_EULA = "1"
  rpi-specific: |
    DISABLE_OVERSCAN = "1"
    DISABLE_SPLASH = "1"
    ENABLE_UART = "1"
    ENABLE_I2C = "1"
    RPI_USE_U_BOOT = "1"
    DISTRO_FEATURES:append = " wifi"
    GPU_FREQ = "250"
    WKS_FILE = "sdimage-raspberrypi.wks"
    IMAGE_FSTYPES += "wic.gz wic.bmap"