version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - /usr/share/home-assistant:/config
    network_mode: "host"
    restart: unless-stopped

