version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - /usr/share/home-assistant:/config
    ports:
      - "8123:8123"
    restart: unless-stopped

